name: ${project.name}
main: net.skinsrestorer.SkinsRestorerAPIExample
version: ${project.version}
description: ${project.description}
website: https://skinsrestorer.net/
authors: [McLive]
api-version: 1.13
depend: [SkinsRestorer]

commands:
  api:
    description: SkinsRestorer API test